config/routes.rb
Rails.application.routes.draw do
  get "transition/graph", :to => "transitions#graph", :as => 'transition_graphs'
  resources :transitions
  get "mega_assembles", :to => "assembly_nums#mega_assemble", :as => 'mega_assembles'
  resources :assembly_nums
  resources :next_battles
  resources :blocks
  resources :partnerships
  resources :intentions
  get "reward/graph", :to => "rewards#graph", :as => 'reward_graphs'
  resources :rewards
  resources :conditions
  resources :regalia
  resources :specs
  resources :statuses
  resources :markets
  resources :items
  resources :proper_names
  resources :names
  get 'top_page/privacy'
  root 'top_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
    @latest_result = Name.maximum('result_no')
    @last_generate = Name.where(result_no: @latest_result).maximum('generate_no')
  end
end

app/views/top_page/index.html.haml
%h1 第2回ゼロ城試遊会データ小屋
%p
  このサイトでは『
  %a{:href => "http://blacktea.sakura.ne.jp/teaconvini/", :target => "_blank"} ゼロの城砦
  』の第2回試遊会を解析して得られる情報を扱っていました。
  %br
  ゲーム運営終了に伴い、全結果から取得したデータを残しています。
%br
%p 
  第#{top_result_no(@latest_result, @last_generate)}更新結果まで反映済です。
%p{style: "font-size:x-large;"} 
  = link_to "⇒次期：ゼロ城データ小屋", "https://data.teiki.org/zero/"

.card.top
  .card-body
    %h2 サイトマップ
    .row
      .col-md-6
        %ul
          %li 個人データ
          %ul  
            %li= link_to "アイテム一覧", items_path
            %li= link_to "ステータス一覧", statuses_path
            %li= link_to "城塞データ一覧", specs_path
            %br
            %li= link_to "精算一覧", rewards_path
            %li= link_to "精算グラフ", reward_graphs_path
            %br
            %li= link_to "メガアセンブル一覧", mega_assembles_path
      .col-md-6
        %ul
          %li 結果データ
          %ul  
            %li= link_to "マーケット一覧", markets_path
            %br
            %li= link_to "戦場別戦果一覧", blocks_path
            %li= link_to "次回組み合わせ一覧", next_battles_path
            %br
            %li= link_to "戦果推移一覧", transitions_path
            %li= link_to "戦果推移グラフ", transition_graphs_path

.card.top
  .card-body
    %h2 更新履歴
    %ul
      %li 2018/12/13
      %ul
        %li サイト公開

app/views/top_page/privacy.html.haml
%h1 プライバシーポリシー
%p 本文書は、当サイト（ゼロ城データ小屋）における個人情報の保護およびその適切な取り扱いについての方針を示したものです。
%br
%h2 当サイトが利用しているアクセス解析ツールに関して
%p (Googleアナリティクス等を使用している場合に記述)
%br
%p 最終更新日：20--年-月-日
%br